web:
    build: .
    ports:
        - "80:80"
    links:
        - db
        - redis-server
    environment:
        - RACK_ENV=development
        - BIND_HOST=0.0.0.0
        - BIND_PORT=80
        - CACHE_HOST=redis-server
        - CACHE_PORT=6379
        - CACHE_ENABED=true
        - MONGODB_HOST=db
        - MONGODB_PORT=27017
        - MONGODB_DBNAME=vidfeeder
        - API_KEY=fake
worker:
    build: .
    dockerfile: docker/worker/Dockerfile
    links:
        - web
        - redis-server
    environment:
        - CACHE_HOST=redis-server
        - CACHE_PORT=6379
        - CACHE_ENABED=true
        - API_HOST=web
        - API_PORT=80
        - API_KEY=fake
db:
    image: mongo
redis-server:
    image: redis
